// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.guerreros.Entities
{
    public partial class ClinicalStudy
    {
        public int Id { get; set; }
        public int StudiesCliniciansId { get; set; }
        public DateTime PublicationDate { get; set; }
        public string MainIntervention { get; set; }
        public string ProtocolNumber { get; set; }
        public string AgeRange { get; set; }
        public int? StudyTypeId { get; set; }
        public string Description { get; set; }

        public virtual StudiesClinicians StudiesClinicians { get; set; }
        public virtual StudyType StudyType { get; set; }
    }
}