// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.guerreros.Entities
{
    public partial class InclusionCriteria
    {
        public int Id { get; set; }
        public int StudiesCliniciansId { get; set; }
        public string CriteriaLong { get; set; }
        public string CriteriaSmall { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public DateTime RegistrationDate { get; set; }

        public virtual StudiesClinicians StudiesClinicians { get; set; }
    }
}