// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.guerreros.Entities
{
    public partial class InformationGuerreros
    {
        public int Id { get; set; }
        public string About { get; set; }
        public string NoticePrivacy { get; set; }
        public DateTime RegistrationDate { get; set; }
    }
}