// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.guerreros.Entities
{
    public partial class Leaflet
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int StudyCategoryId { get; set; }
        public int ClinicalStudyId { get; set; }
        public string MailReason { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    }
}