// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.guerreros.Entities
{
    public partial class Postulation
    {
        public int Id { get; set; }
        public string PatientCode { get; set; }
        public string Name { get; set; }
        public string Suffering { get; set; }
        public string RelevantDate { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public DateTime RegistrationDate { get; set; }
        public int? UserId { get; set; }
        public bool? Active { get; set; }
        public int? StudiesCliniciansId { get; set; }

        public virtual StudiesClinicians StudiesClinicians { get; set; }
        public virtual Users User { get; set; }
    }
}