// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.guerreros.Entities
{
    public partial class ShareClinicalStudies
    {
        public int Id { get; set; }
        public int StudiesCliniciansId { get; set; }
        public int? UserId { get; set; }
        public DateTime? CreationDate { get; set; }

        public virtual StudiesClinicians StudiesClinicians { get; set; }
        public virtual Users User { get; set; }
    }
}