// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.guerreros.Entities
{
    public partial class SponsorsGuerrerosDetail
    {
        public int Id { get; set; }
        public int SponsorGuerrerosId { get; set; }
        public string ImageSponsor { get; set; }
        public string Description { get; set; }
        public int? SponsorTypeId { get; set; }

        public virtual SponsorType SponsorType { get; set; }
    }
}