// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.guerreros.Entities
{
    public partial class StudyCategory
    {
        public StudyCategory()
        {
            News = new HashSet<News>();
            StudiesClinicians = new HashSet<StudiesClinicians>();
            SupportPrograms = new HashSet<SupportPrograms>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string PathImage { get; set; }
        public string PathImageAvatar { get; set; }

        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<StudiesClinicians> StudiesClinicians { get; set; }
        public virtual ICollection<SupportPrograms> SupportPrograms { get; set; }
    }
}