// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.guerreros.Entities
{
    public partial class Suffering
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}