// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.guerreros.Entities
{
    public partial class SupportPrograms
    {
        public SupportPrograms()
        {
            SupportProgramsDetail = new HashSet<SupportProgramsDetail>();
        }

        public int Id { get; set; }
        public int StudyCategoryId { get; set; }
        public string ProgramTitle { get; set; }
        public string ProgramContent { get; set; }
        public DateTime PublicationDate { get; set; }
        public bool Active { get; set; }
        public string Summary { get; set; }
        public bool? Approved { get; set; }

        public virtual StudyCategory StudyCategory { get; set; }
        public virtual ICollection<SupportProgramsDetail> SupportProgramsDetail { get; set; }
    }
}