// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.guerreros.Entities
{
    public partial class Users
    {
        public Users()
        {
            Postulation = new HashSet<Postulation>();
            ShareClinicalStudies = new HashSet<ShareClinicalStudies>();
        }

        public int Id { get; set; }
        public int SpecialtyId { get; set; }
        public string Name { get; set; }
        public string Avatar { get; set; }
        public DateTime BirthDate { get; set; }
        public int GenderId { get; set; }
        public string ProfessionalLicense { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool? Active { get; set; }
        public string Token { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string VerificationCode { get; set; }
        public bool? Verified { get; set; }

        public virtual Specialty Specialty { get; set; }
        public virtual ICollection<Postulation> Postulation { get; set; }
        public virtual ICollection<ShareClinicalStudies> ShareClinicalStudies { get; set; }
    }
}